version: "3.7"

services:
  postgres:
    image: postgres:15.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=ar_enc_example_development
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    container_name: app
    build:
      context: .
      target: dev
      args:
        bundle_install_options: --jobs 10
      cache_from:
        - ar-enc-example-app
    volumes:
      - ./:/app:cached
    environment:
      RAILS_LOG_TO_STDOUT: 1
      TZ: Asia/Tokyo
      AR_ENC_PRIMARY_KEY: e9afd0341ae5673010bda098db826ce3
      AR_ENC_DETERMINISTIC_KEY: 0jefyhajq3hnr96sldPoqu8ISFpI9zRZ
      AR_ENC_KEY_DERIVATION_SALT: q6o3RhCV1hoiGqWnQEgVKGwZQieFrgcF
    ports:
      - 3001:3000
    tty: true
    command: /bin/sh -l -c 'bundle && bin/rails s'
    depends_on:
      - postgres

volumes:
  pgdata:
    driver: local
