default: &default
  adapter: postgresql
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *default
  database: ar_enc_example_development
  password: postgres

test:
  <<: *default
  database: ar_enc_example_test
  password: postgres

production:
  <<: *default
  database: ar_enc_example_production
  username: ar_enc_example
  password: <%= ENV["AR_ENC_EXAMPLE_DATABASE_PASSWORD"] %>
